inherit_from: .rubocop-todo.yml

require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "vendor/**"
    - "bin/**"
    - "lib/**"
    - "db/**"
    - "config/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/bundle/**/*"
    - Gemfile
    - config/unicorn.rb
    - config/unicorn_staging.rb

AsciiComments:
  Enabled: false

Lambda:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

AndOr:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: true

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space

# Use `{ a: 1 }` not `{a:1}`.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
