version: 2.1
# orbs:
#   aws-ecr: circleci/aws-ecr@6.4.0
#   aws-ecs: circleci/aws-ecs@1.0.0
executors:
  default:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          RAILS_ENV: test
      - image: mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    working_directory: ~/app
jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - save_cache:
          key: app-code-{{ .Environment.CIRCLE_SHA1 }}
          paths: ~/app
  bundle_install:
    executor: default
    steps:
      - restore_cache:
          key: app-code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: app-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: install dependencies
          command: |
            bundle install
      - save_cache:
          key: app-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  test_rspec:
    executor: default
    steps:
      - restore_cache:
          key: app-code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: app-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: install bundle
          command: bundle install
      - run:
          name: Database setup
          command: |
            - bundle exec rails db:create db:schema:load
            - bundle exec ridgepole -c config/database.yml -E test --apply -f db/Schemafile
      - run: bundle exec rspec spec/
workflows:
  version: 2
  test:
    jobs:
      - checkout_code
      - bundle_install:
          requires:
            - checkout_code
      - test_rspec:
          requires:
            - bundle_install
