default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('RDS_HOST', 'db') %>
  database: <%= ENV.fetch('RDS_DATABASE', '') %>
  username: <%= ENV.fetch('RDS_USERNAME', 'root') %>
  password: <%= ENV.fetch('RDS_PASSWORD', 'password') %>
  port: 3306
